# Generated by Django 2.1.7 on 2021-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0002_auto_20210419_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops_all',
            name='open',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='shops',
            unique_together={('name', 'city', 'street')},
        ),
    ]
